[[main]]
  name = "নাহু"
  url = "/nahw/tarif/"
  weight = 10

# [[social]]
#   name = "Facebook"
#   pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-facebook\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
#   url = "https://twitter.com/arbipathshala"
#   weight = 10

# [[social]]
#   name = "GitHub"
#   pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
#   url = "https://github.com/h-enk/doks"
#   post = "v0.1.0"
#   weight = 20

[[nahw]]
  name = "নাহু"
  weight = 10
  identifier = "nahw"
  url = "/nahw/tarif/"

[[nahw]]
  name = "নাহুর আলোচনার বিষয়"
  weight = 20
  identifier = "moudu_ilm_nahw"
  url = "/nahw/kalimah/"

[[nahw]]
  name = "কালিমাহর প্রকারভেদ"
  weight = 30
  identifier = "anwanul_kalimah"
  url = "/nahw/ism/"

[[nahw]]
  name = "ইসমের বৈশিষ্ট"
  weight = 40
  identifier = "sifatul_kalimah"
  url = "/nahw/ism/"

[[nahw]]
  name = "মুজাক্কার মুয়ান্নাস বা লিঙ্গ"
  weight = 50
  identifier = "ism_tadhkir_taanis"
  url = "/nahw/ism_tadhkir_taanis/"

[[nahw]]
  name = "মারিফাহ নাকিরাহ বা নির্দিষ্টতা"
  weight = 50
  identifier = "marifa_nakira"
  url = "/nahw/marifa_nakira/"

[[nahw]]
  name = "মুফরাদ, মুসান্না, জামে বা বচন "
  weight = 60
  identifier = "ism_adad"
  url = "/nahw/ism_adad/"

[[nahw]]
  name = "বহুবচনের প্রকারভেদ"
  weight = 70
  identifier = "anwanul_jame"
  url = "/nahw/jame/"

[[nahw]]
  name = "ইসমের ইরাব"
  weight = 80
  identifier = "irabul_ism"
  url = "/nahw/ism_irab/"

[[nahw]]
  name = "রফা / মারফু ইসমের চিহ্ন বা আলামত"
  weight = 80
  identifier = "alamatul_marfu"
  url = "/nahw/ism_marfu/"

[[nahw]]
  name = "রফা / মারফু ইসমের স্থানসমূহ"
  weight = 90
  identifier = "marfuaat"
  url = "/nahw/fail/"

[[nahw]]
  name = "নসব / মানসুব ইসমের চিহ্ন বা আলামত"
  weight = 100
  identifier = "alamatul_mansub"
  url = "/nahw/ism_mansub/"

[[nahw]]
  name = "নসব / মানসুব ইসমের স্থানসমূহ"
  weight = 110
  identifier = "mansubaat"
  url = "/nahw/maful_bihi/"

[[nahw]]
  name = "জার / মাজরুর / খফদ / মাখফুদ ইসমের চিহ্ন বা আলামত"
  weight = 120
  identifier = "alamatul_majrur"
  url = "/nahw/ism_majrur/"